Repository elastic/elasticsearch-dsl-py, pull requests merged in 2024-04, with the labels that each got.

#1634 Resolve _expand__to_dot default at runtime
  elasticsearch_dsl/utils.py
  tests/test_query.py
Labels: bug

#1631 Add MatrixStats aggregation
  elasticsearch_dsl/aggs.py
  tests/test_aggs.py
Labels: enhancement

#1629 Add Geo-Line aggregation
  elasticsearch_dsl/aggs.py
  tests/test_aggs.py
Labels: enhancement

#1595 Add RandomSampler aggregation
  elasticsearch_dsl/aggs.py
  tests/test_aggs.py
Labels: enhancement

#1593 Add IPPrefix aggregation
  elasticsearch_dsl/aggs.py
  tests/test_aggs.py
Labels: enhancement

#1591 Add GeohexGrid aggregation
  elasticsearch_dsl/aggs.py
  tests/test_aggs.py
Labels: enhancement

#1589 Add CategorizeText aggregation
  elasticsearch_dsl/aggs.py
  tests/test_aggs.py
Labels: enhancement

#1615 docs: Fix a few typos
  elasticsearch_dsl/query.py
  examples/async/completion.py
  examples/async/parent_child.py
  examples/completion.py
  examples/parent_child.py
Labels: documentation

#1788 Added "adjacency_matrix" and "top_metrics" aggregations
  elasticsearch_dsl/aggs.py
  tests/test_aggs.py
Labels: backport 8.x

#1787 Fixed documentation example way to access search object
  docs/search_dsl.rst
Labels: backport 8.x

#1814 Revert "Warn when slicing twice (#1775)"
  elasticsearch_dsl/search_base.py
  tests/_async/test_search.py
  tests/_sync/test_search.py
Labels: backport 8.x
